let allMusic = [
    {
      id: 1,
      name: "This Town",
      artist: "Niall Horan",
      img: "./img/This_Town.jpg",
      src: "This Town",
    },
    {
      id: 2,
      name: "Jupiter Mazha",
      artist: "Dhanwin KB",
      img: "./img/Jupiter_Mazha.jpg",
      src: "Jupiter Mazha",
    },
    {
      id: 3,
      name: "Thooriga",
      artist: "Gautham Menon",
      img: "./img/Thooriga.jpg",
      src: "Thooriga",
    },
    {
      id: 4,
      name: "Azhalinte Azhangalil",
      artist: "Nikhil Mathew",
      img: "./img/Azhalinte.jpg",
      src: "Azhalinte",
    },
    {
      id: 5,
      name: "Night Changes",
      artist: "One Direction",
      img: "./img/Night_Changes.jpg",
      src: "Night Changes",
    },
    {
      id: 6,
      name: "Samjhawan",
      artist: "Arijit Singh",
      img: "./img/Arijit_Singh.jpg",
      src: "Samjhawan",
    },
    {
      id: 7,
      name: "Soch Na Sake",
      artist: "Arijit Singh",
      img: "./img/Arijit_Singh.jpg",
      src: "Soch Na Sake",
    },
    {
      id: 8,
      name: "Heat Waves",
      artist: "Glass Animals",
      img: "./img/Glass_Animals.jpg",
      src: "Heat Waves",
    },
    {
      id: 9,
      name: "Adiyae Kolluthey",
      artist: "Harris Jayaraj",
      img: "./img/Adiyae_Kolluthey.jpg",
      src: "Adiyae Kolluthey",
      },
    {
      id: 10,
      name: "death bed",
      artist: "Powfu",
      img: "./img/death_bed.jpg",
      src: "death bed",
    },
    {
      id: 11,
      name: "Nee Kavithaigala",
      artist: "Pradeep Kumar",
      img: "./img/Nee_Kavithaigala.jpg",
      src: "Nee Kavithaigala",
    },
    {
      id: 12,
      name: "Uyire",
      artist: "Minnal Murali",
      img: "./img/Uyire.jpg",
      src: "Uyire",
    },
    {
      id: 13,
      name: "At My Worst",
      artist: "Pink Sweats",
      img: "./img/At_My_Worst.jpg",
      src: "At My Worst",
    },
    {
      id: 14,
      name: "Dandelions",
      artist: "Ruth B",
      img: "./img/Dandelions.jpg",
      src: "Dandelions",
    },
    {
      id: 15,
      name: "Mudhal Nee",
      artist: "Sid Sriram",
      img: "./img/mudhal_nee_mudivum_nee.jpg",
      src: "mudhal nee mudivum nee",
    },
    {
      id: 16,
      name: "Oru Nokk",
      artist: "Arijit Singh",
      img: "./img/oru_nokk.jpg",
      src: "oru nokk",
    },
    {
      id: 17,
      name: "Coastline",
      artist: "Hollow Coves",
      img: "./img/Hollow_Coves.jpg",
      src: "Coastline",
    },
    {
      id: 18,
      name: "Somberi",
      artist: "Havoc Brothers",
      img: "./img/somberi.jpg",
      src: "somberi",
    },
    {
      id: 19,
      name: "Abhi Mujh Mein",
      artist: "Thaikkudam Bridge",
      img: "./img/Abhi_Mujh_Mein.jpg",
      src: "Abhi Mujh Mein",
      },
    {
      id: 20,
      name: "Someone To You",
      artist: "Banners",
      img: "./img/someone_to_you.jpg",
      src: "someone to you",
    },
    {
      id: 21,
      name: "Shivers",
      artist: "Ed Sheeran",
      img: "./img/shivers.jpg",
      src: "shivers",
    },

  ];
