let allMusic = [
    {
      name: "This Town",
      artist: "Niall Horan",
      img: "./img/music-1.jpg",
      src: "music-1",
      bg: "#424242",
    },
    {
      name: "Jupiter Mazha",
      artist: "Dhanwin KB",
      img: "./img/music-2.jpg",
      src: "music-2",
      bg: "#5e35b1",
    },
    {
      name: "Thooriga",
      artist: "Gautham Menon",
      img: "./img/music-3.jpg",
      src: "music-3",
      bg: "#e93e93",
    },
    {
      name: "Azhalinte Azhangalil",
      artist: "Nikhil Mathew",
      img: "./img/music-4.jpg",
      src: "music-4",
      bg: "#3f51b5",
    },
    {
      name: "Night Changes",
      artist: "One Direction",
      img: "./img/music-5.jpg",
      src: "music-5",
      bg: "#333333",
    },
    {
      name: "Samjhawan",
      artist: "Arijit Singh",
      img: "./img/music-6.jpg",
      src: "music-6",
      bg: "#c62828",
    },
    {
      name: "Soch Na Sake",
      artist: "Arijit Singh",
      img: "./img/music-7.jpg",
      src: "music-7",
      bg: "#c62828",
    },
    {
      name: "Heat Waves",
      artist: "Glass Animals",
      img: "./img/music-8.jpg",
      src: "music-8",
      bg: "#e91e63",
    },
    {
      name: "Adiyae Kolluthey",
      artist: "Harris Jayaraj",
      img: "./img/music-9.jpg",
      src: "music-9",
      bg: "#b71c1c",
    },
    {
      name: "death bed",
      artist: "Powfu",
      img: "./img/music-10.jpg",
      src: "music-10",
      bg: "#283593",
    },
    {
      name: "Nee Kavithaigala",
      artist: "Pradeep Kumar",
      img: "./img/music-11.jpg",
      src: "music-11",
      bg: "#1a7a3a",
    },
  ];