let allMusic = [
    {
      id: 1,
      name: "This Town",
      artist: "Niall Horan",
      img: "./img/This_Town.jpg",
      src: "This Town",
      bg: "#424242",
    },
    {
      id: 2,
      name: "Jupiter Mazha",
      artist: "Dhanwin KB",
      img: "./img/Jupiter_Mazha.jpg",
      src: "Jupiter Mazha",
      bg: "#242349",
    },
    {
      id: 3,
      name: "Thooriga",
      artist: "Gautham Menon",
      img: "./img/Thooriga.jpg",
      src: "Thooriga",
      bg: "#C16F73",
    },
    {
      id: 4,
      name: "Azhalinte Azhangalil",
      artist: "Nikhil Mathew",
      img: "./img/Azhalinte.jpg",
      src: "Azhalinte",
      bg: "#3f51b5",
    },
    {
      id: 5,
      name: "Night Changes",
      artist: "One Direction",
      img: "./img/Night_Changes.jpg",
      src: "Night Changes",
      bg: "#333333",
    },
    {
      id: 6,
      name: "Samjhawan",
      artist: "Arijit Singh",
      img: "./img/Arijit_Singh.jpg",
      src: "Samjhawan",
      bg: "#c62828",
    },
    {
      id: 7,
      name: "Soch Na Sake",
      artist: "Arijit Singh",
      img: "./img/Arijit_Singh.jpg",
      src: "Soch Na Sake",
      bg: "#c62828",
    },
    {
      id: 8,
      name: "Heat Waves",
      artist: "Glass Animals",
      img: "./img/Glass_Animals.jpg",
      src: "Heat Waves",
      bg: "#e91e63",
    },
    {
      id: 9,
      name: "Adiyae Kolluthey",
      artist: "Harris Jayaraj",
      img: "./img/Adiyae_Kolluthey.jpg",
      src: "Adiyae Kolluthey",
      bg: "#b71c1c",
      },
    {
      id: 10,
      name: "death bed",
      artist: "Powfu",
      img: "./img/death_bed.jpg",
      src: "death bed",
      bg: "#283593",
    },
    {
      id: 11,
      name: "Nee Kavithaigala",
      artist: "Pradeep Kumar",
      img: "./img/Nee_Kavithaigala.jpg",
      src: "Nee Kavithaigala",
      bg: "#134605",
    },
    {
      id: 12,
      name: "Uyire",
      artist: "Minnal Murali",
      img: "./img/Uyire.jpg",
      src: "Uyire",
      bg: "#1a237e",
    },
    {
      id: 13,
      name: "At My Worst",
      artist: "Pink Sweats",
      img: "./img/At_My_Worst.jpg",
      src: "At My Worst",
      bg: "#d81b60",
    },
    {
      id: 14,
      name: "Dandelions",
      artist: "Ruth B",
      img: "./img/Dandelions.jpg",
      src: "Dandelions",
      bg: "#455a64",
    },
    {
      id: 15,
      name: "Mudhal Nee",
      artist: "Sid Sriram",
      img: "./img/mudhal_nee_mudivum_nee.jpg",
      src: "mudhal nee mudivum nee",
      bg: "#795548",
    },
    {
      id: 16,
      name: "Oru Nokk",
      artist: "Arijit Singh",
      img: "./img/oru_nokk.jpg",
      src: "oru nokk",
      bg: "#0277bd",
    },
    {
      id: 17,
      name: "Coastline",
      artist: "Hollow Coves",
      img: "./img/Hollow_Coves.jpg",
      src: "Coastline",
      bg: "#8d6e63",
    },
    {
      id: 18,
      name: "Somberi",
      artist: "Havoc Brothers",
      img: "./img/somberi.jpg",
      src: "somberi",
      bg: "#BDC109",
    },
    {
      id: 19,
      name: "Abhi Mujh Mein",
      artist: "Thaikkudam Bridge",
      img: "./img/Abhi_Mujh_Mein.jpg",
      src: "Abhi Mujh Mein",
      bg: "#3D505C",
      },
    {
      id: 20,
      name: "Someone To You",
      artist: "Banners",
      img: "./img/someone_to_you.jpg",
      src: "someone to you",
      bg: "#ef6c00",
    },
    {
      id: 21,
      name: "Shivers",
      artist: "Ed Sheeran",
      img: "./img/shivers.jpg",
      src: "shivers",
      bg: "#f44336",
    },

  ];
